server:
  port: 8801

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://service.aliww.top:3306/bjpowernode?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jalivv669


#Whether a request parameter ("format" by default) should be used to determinethe requested media type.
#  mvc:
#    contentnegotiation:
#      favor-parameter: true
logging:
  level:
    com.jalivv.demo: debug


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
